/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    ProjectSection: typeof import('./components/ProjectSection.vue')['default']
    ProjectSectionCol: typeof import('./components/ProjectSectionCol.vue')['default']
    ProjectSectionRow: typeof import('./components/ProjectSectionRow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
